config/routes.rb
Rails.application.routes.draw do
  #gommiクラスのアクションを設定するときはresorces :gommisよりも上に書かないとダメ
  get 'gommis/pick' => 'gommis#pick'
  get 'gommis/complete' => 'gommis#complete'
  get 'gommis/lttr' => 'gommis#lttr'
  get 'gommis' => 'home#root'
  get 'gommis/a1k2a34ik4e444i4k4e4i44k4e44go456347g437oy4a363y47a54t573o7t3o535s73a745s34a375s54i753s7543i4s5u43s73u34' => 'gommis#index'
  resources :gommis
  # get 'home/root
  root 'home#root'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gommi.rb
class Gommi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gommis_controller.rb
class GommisController < ApplicationController
  before_action :set_gommi, only: [ :edit, :update, :destroy]

  # GET /gommis
  # GET /gommis.json
  def index
    @gommis = Gommi.all
  end
  # GET /gommis/1
  # GET /gommis/1.json

def pick
  @gommis_count = Gommi.count
  @gommis = Gommi.offset(rand(Gommi.count)).first
end

def lttr
  @gommis = Gommi.offset(rand(Gommi.count)).first

end

def complete
end
  # GET /gommis/new
  def new
    @gommi = Gommi.new
  end

  # GET /gommis/1/edit
  def edit
  end

  # POST /gommis
  # POST /gommis.json
  def create
    @gommi = Gommi.new(gommi_params)

    respond_to do |format|
      if @gommi.save
        format.html { redirect_to gommis_complete_path, notice: 'Gommi was successfully created.' }
        format.json { render :show, status: :created, location: @gommi }
      else
        format.html { render :new }
        format.json { render json: @gommi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gommis/1
  # PATCH/PUT /gommis/1.json
  def update
    respond_to do |format|
      if @gommi.update(gommi_params)
        format.html { redirect_to @gommi, notice: 'Gommi was successfully updated.' }
        format.json { render :show, status: :ok, location: @gommi }
      else
        format.html { render :edit }
        format.json { render json: @gommi.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /gommis/1
  # DELETE /gommis/1.json
  def destroy
    @gommi.destroy
    respond_to do |format|
      format.html { redirect_to gommis_url, notice: 'Gommi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gommi
      @gommi = Gommi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gommi_params
      params.require(:gommi).permit(:title, :explanation, :kind)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gommis_helper.rb
module GommisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gommis/_form.html.erb
<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});
$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>


<div class="gommiForm">
  <%= form_with(model: gommi, local: true) do |form| %>
    <% if gommi.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gommi.errors.count, "error") %> prohibited this gommi from being saved:</h2>

        <ul>
        <% gommi.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<div class="forms">
  <h1>ぜんぶうみにながそう</h1>
  <div class="field">
    <%= form.text_field :title, placeholder: "たいとる", class: 'title_textfield textfield'%>
  </div>

  <div class="field">
    <%= form.text_area :explanation, placeholder: "くわしくかきたかったらどうぞ", class: 'explanation_textfield textfield'%>
  </div>

  <div class="field">
    <%= form.select :kind, [["芸術", "芸術"],["サービス","サービス"],["ゲーム","ゲーム"],["レシピ","レシピ"]], prompt: "しゅるいをせんたくしてね", class: 'kind_textfield textfield' %>
  </div>
</div>

    <div class="actions">
      <%= image_submit_tag "binButton.png",style: "position: absolute; left: 73%; top: 65%; onmouseover: \"this.style.width=19%\"", id: "binButton" %>
    </div>
  <% end %>

</div>

app/views/gommis/complete.html.erb
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<div class="gommis_complete">

  <h1>ながしました !</h1>
  <!-- <%=image_tag(src = "/assets/dustBox", size: 17*17, class: "dustBox")%> -->

  <div class="boxContainer">
            <a href="/gommis/new" class="square_btn">もういちどながしにいく</a>

            <a href="/gommis/pick" class="square_btn">ひろいにいく</a>
  </div>
  <div id="canvas-container">
    <%= image_tag(src = "/assets/flowedBin.png", style: " position:  absolute; z-index: 1; width: 9%;", id:"flowedBi")%>
      <canvas id="sineCanva" width="800" height="300"></canvas>
  </div>
</div>
<%= image_tag(src = "/assets/ground.png", style: "position: absolute; left: 0px; bottom: 0px; width: 100%; z-index: -1", id:"stone")%>

<%= javascript_include_tag "waveforComplete.js" %>

app/views/gommis/edit.html.erb
<h1>Editing Gommi</h1>

<%= render 'form', gommi: @gommi %>

<%= link_to 'Show', @gommi %> |
<%= link_to 'Back', gommis_path %>

app/views/gommis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gommis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Explanation</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gommis.each do |gommi| %>
      <tr>
        <td><%= gommi.title %></td>
        <td><%= gommi.explanation %></td>
        <td><%= gommi.kind %></td>
        <td><%= link_to 'Show', gommi %></td>
        <td><%= link_to 'Edit', edit_gommi_path(gommi) %></td>
        <td><%= link_to 'Destroy', gommi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gommi', new_gommi_path %>

app/views/gommis/lttr.html.erb
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});
$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>


<div class="show">
  <div class="onPaper">
    <%=image_tag("/assets/paper.png", style: "width:100%; z-index: -1")%>
    <div class="moji">
      <p class="title">
        <%= @gommis.title %>
      </p>

      <p class="explanation">
        <%= @gommis.explanation %>
      </p>

      <p class="kind">
        <%= @gommis.kind %>
      </p>
    </div>
  </div>

<div class="pickbin">

  <%= link_to image_tag("/assets/roson2.png"), gommis_pick_path %>
</div>
</div>

<%= image_tag(src = "/assets/sunahama.png", style: "position: absolute; left: 0px; bottom: 0px; width: 100%; z-index: -1", id:"stone")%>

app/views/gommis/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});

$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>


<body>
<div class="gommi_new">

  <%= render 'form', gommi: @gommi %>

<div class="iwa">
<%= image_tag(src = "/assets/ground.png", style: "position: absolute; left: 0px; bottom: 0px; width: 100%; z-index: -1", id:"stone")%>
</div>
</div>

</body>

app/views/gommis/pick.html.erb
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});
$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>


<div class="pick">
  <br><br><br>
  <h1>びんをはっけん</h1>
  <div class="pyon">
  <%=link_to(image_tag("/assets/synahama_bin.png", style:"position: absolute; top: 60%; left: 38%;height: 30%;", id: "pyonBin"), "#{Gommi.offset(rand(Gommi.count)).first.id}")%>
</div>
</div>
<%= image_tag(src = "/assets/sunahama.png", style: "position: absolute; left: 0px; bottom: 0px; width: 100%; z-index: -1", id:"stone")%>




<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/gommis/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});
$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>


<div class="show">
  <div class="onPaper">
    <%=image_tag("/assets/paper.png", style: "width:100%; z-index: -1")%>
    <div class="moji">
      <p class="title">
        <%= @gommi.title %>
      </p>

      <p class="explanation">
        <%= @gommi.explanation %>
      </p>

      <p class="kind">
        <%= @gommi.kind %>
      </p>
    </div>
  </div>

<div class="pickbin">
  <!-- <%= link_to 'Edit', edit_gommi_path(@gommi) %> |
  <%= link_to 'Back', gommis_path %> -->
  <%= link_to image_tag("/assets/roson2.png"), gommis_pick_path %>
</div>
</div>

<%= image_tag(src = "/assets/sunahama.png", style: "position: absolute; left: 0px; bottom: 0px; width: 100%; z-index: -1", id:"stone")%>

app/views/home/root.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
<title>home</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<script src="jquery-3.3.1.min.js"></script>
<script>
$(function(){
  $(".headC").click(function(){
    $(".headB").slideToggle();
  });
});
</script>
</head>

<body>



<div class="conA">
  <div class="container">
    <p>だれかに<span id="sent">届く</span>といいですね。</p>
    <h1> bottle </h1>
  </div>

<div class="box">
        <a href="/gommis/new" class="square_btn">ながしにいく</a>

        <a href="/gommis/pick" class="square_btn">ひろいにいく</a>
      </div>



<div id="canvas-container">
  <%= image_tag(src = "/assets/flowedBin.png", style: " position:  absolute; z-index: 1; width: 9%;", id:"flowedBi")%>
    <canvas id="sineCanva"></canvas>
  </div>

</div>
<img class="groundImage" src="assets/ground.png">


</body>
</html>

<%= javascript_include_tag "waveforComplete.js" %>

app/views/layouts/_header.html.erb
<!--ここからちょっとよくわからないです-->
<script src="jquery-3.3.1.min.js"></script>
<script>
$(document).ready(function(){
    $('.headB').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').slideToggle();
        }
    });
    $('.headC').click(function(){
        if($(window).width() > 767){
        } else{
            $('nav').hide();
        }
    });
});
$(window).resize(function(){
    if($(window).width() > 767){
        $('nav').show();
    } else{
        $('nav').hide();
    }
});
</script>

<!--ここまでです-->


  <header>
    <div class="container">
      <div class="container-small">
        <a href="/" class="headA">Bottle</a>

      <button type="button" class="headC">
        <span class="fas fa-bars" title="MENU"></span>
      </button>
    </div>

      <nav class="headB">
        <ul>
          <li><a href="/gommis/new" class="headB" >ながす</a></li>
            <li><a href="/gommis/pick" class="headB">ひろう</a></li>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottle</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "layouts/header"%>
    <%= yield %>

  </body>
</html>